"""Rows the coordinator and venue tests insert into the public tables.

Each test inserts what it needs through `AppTestCase.seed_*` inside a transaction
that is rolled back afterwards, so none of this is ever saved. Emails get a
per-run suffix (see tests/base.py) so parallel test runs never collide.

For venues, None means "not recorded". An empty list, False or 0 means the venue
was recorded as having none of that thing, which is a confirmed fact.
"""

from datetime import datetime

USERS = [
    {"key": "admin", "email": "admin@connectsphere.test", "role": "admin"},
    {"key": "alice", "email": "alice.coordinator@connectsphere.test", "role": "coordinator"},
    {"key": "ben", "email": "ben.coordinator@connectsphere.test", "role": "coordinator"},
    {"key": "chloe", "email": "chloe.coordinator@connectsphere.test", "role": "coordinator"},
    {"key": "dana", "email": "dana.organiser@connectsphere.test", "role": "organiser"},
    {"key": "evan", "email": "evan.organiser@connectsphere.test", "role": "organiser"},
    {"key": "farah", "email": "farah.attendee@connectsphere.test", "role": "attendee"},
    {"key": "gus", "email": "gus.venue@connectsphere.test", "role": "venue_staff"},
    {"key": "hana", "email": "hana.tech@connectsphere.test", "role": "tech_staff"},
]

# `organiser` and `coordinator` refer to USERS keys.
EVENTS = [
    {
        "key": "unassigned",
        "title": "Tech Summit 2026",
        "status": "submitted",
        "organiser": "dana",
        "start_time": datetime(2026, 11, 10, 9, 0),
        "end_time": datetime(2026, 11, 10, 17, 0),
        "coordinator": None,
        "coordinator_assigned_at": None,
    },
    {
        "key": "assigned",
        "title": "Charity Gala",
        "status": "submitted",
        "organiser": "dana",
        "start_time": datetime(2026, 12, 5, 18, 0),
        "end_time": datetime(2026, 12, 5, 23, 0),
        "coordinator": "alice",
        "coordinator_assigned_at": datetime(2026, 9, 1, 10, 0),
    },
    {
        "key": "evans_event",
        "title": "Product Launch",
        "status": "submitted",
        "organiser": "evan",
        "start_time": datetime(2026, 11, 20, 14, 0),
        "end_time": datetime(2026, 11, 20, 16, 0),
        "coordinator": "ben",
        "coordinator_assigned_at": datetime(2026, 9, 2, 15, 30),
    },
    {
        "key": "draft",
        "title": "Draft Workshop",
        "status": "draft",
        "organiser": "dana",
        "start_time": datetime(2027, 1, 15, 10, 0),
        "end_time": datetime(2027, 1, 15, 12, 0),
        "coordinator": None,
        "coordinator_assigned_at": None,
    },
    {
        "key": "cancelled",
        "title": "Cancelled Meetup",
        "status": "cancelled",
        "organiser": "dana",
        "start_time": datetime(2026, 10, 30, 19, 0),
        "end_time": datetime(2026, 10, 30, 21, 0),
        "coordinator": None,
        "coordinator_assigned_at": None,
    },
]

VENUES = [
    {  # Every planning field recorded.
        "key": "fully_recorded",
        "name": "Aurora Ballroom",
        "description": "Pillarless ballroom with a sprung dance floor and harbour views.",
        "location": "Level 3, Marina Tower, 10 Bayfront Ave",
        "capacity": 400,
        "area_sqm": 850,
        "is_available": True,
        "facilities": ["Stage", "Projector", "PA system", "Wi-Fi", "Green room"],
        "accessibility_features": ["Wheelchair ramp", "Accessible toilets", "Hearing loop"],
        "room_layouts": ["theatre", "banquet", "cabaret", "cocktail"],
        "operating_hours": "Mon-Sun 08:00-23:00",
        "contact_email": "events@marinatower.test",
        "contact_phone": "+65 6123 4567",
        "parking_spaces": 120,
        "catering_available": True,
    },
    {  # Only location and facilities recorded.
        "key": "partially_recorded",
        "name": "Bayfront Pavilion",
        "description": None,
        "location": "Bayfront Park, East Lawn",
        "capacity": None,
        "area_sqm": None,
        "is_available": True,
        "facilities": ["Covered stage"],
        "accessibility_features": None,
        "room_layouts": None,
        "operating_hours": None,
        "contact_email": None,
        "contact_phone": None,
        "parking_spaces": None,
        "catering_available": None,
    },
    {  # Recorded as offering none of these: confirmed absences, not missing data.
        "key": "recorded_as_none",
        "name": "Civic Hall",
        "description": "Community hall available for bare-venue hire.",
        "location": "12 Civic Road",
        "capacity": 80,
        "area_sqm": 150,
        "is_available": True,
        "facilities": [],
        "accessibility_features": [],
        "room_layouts": ["theatre"],
        "operating_hours": "Mon-Fri 09:00-18:00",
        "contact_email": "hire@civichall.test",
        "contact_phone": "+65 6000 1111",
        "parking_spaces": 0,
        "catering_available": False,
    },
    {  # Recorded, but not currently bookable; it must still be browsable.
        "key": "unavailable",
        "name": "Dockside Studio",
        "description": "Industrial studio, closed for renovation until Q1 2027.",
        "location": "Pier 4, Harbourfront",
        "capacity": 60,
        "area_sqm": 200,
        "is_available": False,
        "facilities": ["Blackout blinds", "Lighting rig"],
        "accessibility_features": ["Step-free entrance"],
        "room_layouts": ["classroom", "boardroom"],
        "operating_hours": "By appointment",
        "contact_email": "studio@dockside.test",
        "contact_phone": None,
        "parking_spaces": 10,
        "catering_available": False,
    },
    {  # Blank strings were typed in but carry no information.
        "key": "blank_values",
        "name": "Evergreen Loft",
        "description": "   ",
        "location": "",
        "capacity": 50,
        "area_sqm": None,
        "is_available": True,
        "facilities": ["Kitchenette"],
        "accessibility_features": None,
        "room_layouts": ["u_shape"],
        "operating_hours": "  ",
        "contact_email": "",
        "contact_phone": None,
        "parking_spaces": None,
        "catering_available": None,
    },
]
